services:
  apppy:
    build:
      context: ./apppy
      dockerfile: Dockerfile
    links:
      - "mariadb"
    networks:
      net-tp4:

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: foo
    volumes:
      - './mariadb/vol-sql-demo:/var/lib/mysql'
    ports:
      - 3307:3306
    networks:
      net-tp4:


networks:
  net-tp4:
    driver: bridge